CREATE DATABASES  jd2_homework9_10;

USE jd2_homework9_10;

DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS user_information;

CREATE TABLE IF NOT EXISTS user(
id INT PRIMARY KEY AUTO_INCREMENT,
username VARCHAR(40) NOT NULL,
password VARCHAR(40) NOT NULL,
is_active TINYINT(1) NOT NULL DEFAULT true,
age INT(11) NOT NULL);

CREATE TABLE IF NOT EXISTS user_information(
user_id INT PRIMARY KEY,
address VARCHAR(100) NOT NULL,
telephone VARCHAR(40) NOT NULL,
FOREIGN KEY (user_id) REFERENCES user(id) ON DELETE CASCADE);